= How to setup a project using bower and angularjs $resource
Ernst Vorsteveld
:toc: left
:doctype: book
:docinfo:

== Requirements

Installation of components below is required:

* jdk 8
* node package manager npm (`brew install node`)
* bower (`npm install -g bower`)


== Bower configuration
Bower configuration consists of two files:

* .bowerrc
* bower.json

=== .bowerrc
In this file we configure the directory where bower will write components to.

[source, json]
----
{
  "directory": "src/main/resources/static/components/"
}
----

=== bower.json
This file contains the bower configuration. Find Bower information on the internet.

Example:
[source,json]
----
{
  "name": "example-resource",
  "authors": [
    "Ernst Vorsteveld <ernst.vorsteveld@gmail.com>"
  ],
  "description": "Test using $resource of angularjs",
  "main": "",
  "moduleType": [],
  "license": "MIT",
  "homepage": "",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "~1.4.8",
    "angular-ui-bootstrap": "0.14.3",
    "angular-route" :"1.4.8",
    "angular-mocks" : "1.4.8",
    "angular-resource" : "1.4.8"
  }
}
----
=== install bower managed dependencies

Execute for installation dependencies run: `bower update`

=== install node module dependencies

To install node dependencies run: `npm update`

== URLS

I added a constant for specification of some constant values. I also used the persons controller url.
This is not how you would expect it (this url should be defined in the person.factory.js. It is only created for
showing how it could work.

== Resource usage

The Person factory uses a angularjs $resource. It shows how you can retrieve a single user and all the users.

== Test and generate report

Code coverage report for java is generated on:
`./gradlew clean test jacoco`

result: build/jacocoHtml/index.html

Code coverage report for javascript is generated on:
`./gradlew clean karmaRun`

result: build/coverage/PhantomJS%202.1.1%20(Mac%20OS%20X%200.0.0)/index.html

unit test report:
build/reports/tests/index.html

== Swagger

Find swagger documentation on-line:

Point your browser to: `http://localhost:8080/swagger-ui.html`

== Application

Point your browser to: `http://localhost:8080`
